version: '3.8'
services:

  front-end:
#    image: anur4ik/front-ssd //
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: front-end
    environment:
      domainOfServer:
    ports:
      - "8081:8081"
    networks:
      - ssd_network

  server:
    image: user980/ssd_app_server                    #openjdk:17-jdk-alpine
    container_name: server
    depends_on:
      - postgres
      - redis
    environment:
      dburl: jdbc:postgresql://postgres:5432/SSD    #SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SSD
      dbuser: postgres                            #SPRING_DATASOURCE_USERNAME: postgres
      dbpass: root                                    #SPRING_DATASOURCE_PASSWORD: root

      redishost: redis                                #SPRING_REDIS_HOST: redis
      redisport: 6379                                #SPRING_REDIS_PORT: 6379

      fdomain: http://host-176-36-217-137.b024.la.net.ua

    ports:
      - "8080:8080"
    volumes:
      - ./target/SSD-0.0.1-SNAPSHOT.jar:/server/SSD-0.0.1-SNAPSHOT.jar
    command: [ "java", "-jar", "/server/SSD-0.0.1-SNAPSHOT.jar" ]
    networks:
      - ssd_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      # Конфігурації серверів
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # Папка для certbot challenge
      - ./nginx/html:/var/www/html:rw
      # Сертифікати, отримані certbot
      - ./nginx/certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front-end
      - server
    networks:
      - ssd_network


#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d:ro
#      - ./nginx/html:/var/www/html:rw
#    ports:
#      - "80:80"
#    depends_on:
#      - front-end
#      - server
#    networks:
#      - ssd_network


  postgres:
    image: postgres:14
    container_name: ssd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SSD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ssd_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ssd_network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/html --email denzeml313@gmail.com --agree-tos --no-eff-email -d host-176-36-217-137.b024.la.net.ua"
      
      networks:
      - ssd_network



volumes:
  postgres_data:

networks:
  ssd_network:
    driver: bridge
