spring.application.name=SSD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${dburl:jdbc:postgresql://localhost:5432/SSD}
spring.datasource.username=${dbuser:postgres}
spring.datasource.password=${dbpass:root}

spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.current_session_context_class=thread
server.port=${port:8080}
spring.jpa.hibernate.ddl-auto=${jpaddl:none}

spring.data.redis.host=${redishost:localhost}
spring.data.redis.port=${redisport:6379}

jwt.secret=${jwtsecrer:_[YKB%ugs>c|9%JeWDN0Nxev+#CY;05}pTM`#}
jwt.issuer=MociakaDenys
jwt.expiration.minutes=600000

ssd.domain=${fdomain:http://host-176-36-217-137.b024.la.net.ua}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duiktssd@gmail.com
spring.mail.password=bppgjnhwlcaumkxg
spring.mail.test-connection=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.sender.email=StudSamoD@gmail.com
spring.mail.sender.text=SSD
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



